/*
 * generated by Xtext 2.32.0
 */
package co7217.week17.entity.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link EntityDSLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractEntityDSLWebModule extends DefaultWebModule {

}
