/*
 * generated by Xtext 2.32.0
 */
package co7217.week17.entity.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EntityDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("co7217/week17/entity/parser/antlr/internal/InternalEntityDSL.tokens");
	}
}
