/**
 * generated by Xtext 2.32.0
 */
package co7217.week17.entity.generator;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class EntityDSLGenerator /* implements AbstractGenerator  */{
  public void doGenerate(final /* Resource */Object resource, final /* IFileSystemAccess2 */Object fsa, final /* IGeneratorContext */Object context) {
  }
}
