/*
 * generated by Xtext 2.32.0
 */
package co7217.week17.entity;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EntityDSLStandaloneSetup extends EntityDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new EntityDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
