/**
 * generated by Xtext 2.32.0
 */
package co7217.week17.entity.tests;

/* @ExtendWith(_InjectionExtension)
@InjectWith(_EntityDSLInjectorProvider)
 */public class EntityDSLParsingTest {
  /* @Inject
   */private /* ParseHelper<Domainmodel> */Object parseHelper;

  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assertions is undefined"
      + "\nThe method or field Assertions is undefined"
      + "\nThe field EntityDSLParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\nassertNotNull cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nassertTrue cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
