/**
 * generated by Xtext 2.32.0
 */
package co7217.week17.entity.entityDSL.impl;

import co7217.week17.entity.entityDSL.Entity;
import co7217.week17.entity.entityDSL.EntityDSLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EntityImpl extends TypeImpl implements Entity
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EntityDSLPackage.Literals.ENTITY;
  }

} //EntityImpl
